In [785]:
import numpy as np
import pandas as pd

In [1079]:
objective=np.array([['min',-1,2]], dtype=np.object)
objective

C:\Users\maith\AppData\Local\Temp\ipykernel_12896\494843975.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  objective=np.array([['min',-1,2]], dtype=np.object)


array([['min', -1, 2]], dtype=object)

In [1080]:
constraint=np.array([[-1,-2,'<=',6],[1,-2,'<=',4],[-1,1,'<=',1]], dtype=np.object)
constraint

C:\Users\maith\AppData\Local\Temp\ipykernel_12896\876874134.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  constraint=np.array([[-1,-2,'<=',6],[1,-2,'<=',4],[-1,1,'<=',1]], dtype=np.object)


array([[-1, -2, '<=', 6],
       [1, -2, '<=', 4],
       [-1, 1, '<=', 1]], dtype=object)

In [1081]:
condition=np.array([[1,0,'<=',6],[0,1,'<=',9]], dtype=np.object)
condition

C:\Users\maith\AppData\Local\Temp\ipykernel_12896\2516045595.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  condition=np.array([[1,0,'<=',6],[0,1,'<=',9]], dtype=np.object)


array([[1, 0, '<=', 6],
       [0, 1, '<=', 9]], dtype=object)

In [1082]:
def check_condition(objective, constraint, condition):
    
    for i in range(condition.shape[0]):
        for j in range(condition.shape[1]):
            if np.diag(condition)[i] == 1:
                if condition[i][j] == '<='and condition[:,-1][i] == 0  :
                    objective[:,i+1] = objective[:,i+1]*-1
                    constraint[:,i]=constraint[:,i]*-1
                    condition[i][j] = '>='
                elif condition[i][j]=='<='and condition[:,-1][i] != 0 :
                    newcol=np.vstack([objective[:,2*i+1],objective[:,2*i+1]*-1])
                    temp_objective=pd.DataFrame(objective)
                    temp_objective.insert(2*i+1,None,newcol[0].T)
                    temp_objective.insert(i+2,None,newcol[1].T)
                    temp_objective.drop(labels=2*i+1,axis=1,inplace=True)
                    objective=temp_objective.values
                    
                    newrow= condition[i,:]
                    temp_constraint=pd.DataFrame(constraint)
                    temp_constraint.loc[temp_constraint.shape[0]+0.5]=newrow
                    constraint= np.vstack([constraint, newrow])
                    newcol=np.vstack([constraint[:,i],constraint[:,i]*-1])
                    temp_constraint.insert(2*i,None,newcol[0].T)
                    temp_constraint.insert(2*i+1,None,newcol[1].T)
                    temp_constraint.drop(labels=i,axis=1,inplace=True)
                    constraint=temp_constraint.values
                    
                    newcol=np.zeros(condition.shape[0])
                    newrow=np.zeros(condition.shape[1]+1)
                    temp_condition=pd.DataFrame(condition)
                    temp_condition.insert(condition.shape[1]-2,None,newcol.T)
                    temp_condition.loc[condition.shape[0]]=newrow
                    temp_condition.iloc[-1,condition.shape[1]-1]='>='
                    temp_condition.iloc[-1,condition.shape[1]-2]=1
                    temp_condition.iloc[i,condition.shape[1]]=0
                    temp_condition.iloc[i,condition.shape[1]-1]='>='
                    condition = np.array(temp_condition)
                    
                              
            #if condition[i][j]=='>='and condition[:,-1][i] != '0':
    
        
    return objective,constraint,condition







check_condition(objective, constraint, condition)

(array([['min', -1, 1, -2, 2]], dtype=object),
 array([[-1, 1, -1, -2, '<=', 6],
        [1, -1, 1, -2, '<=', 4],
        [-1, 1, -1, 1, '<=', 1],
        [1, -1, 1, 0, '<=', 6],
        [0, 1, -1, 0.0, '<=', 9]], dtype=object),
 array([[1, 0, 0.0, 0.0, '>=', 0],
        [0, 1, 0.0, 0.0, '>=', 0],
        [0.0, 0.0, 1.0, 0.0, '>=', 0.0],
        [0.0, 0.0, 0.0, 1.0, '>=', 0.0]], dtype=object))