In [1]:
import numpy as np
import pandas as pd

In [2]:
objective=np.array([['max',5,-10]], dtype=np.object)
objective_origin=objective
objective_origin

C:\Users\maith\AppData\Local\Temp\ipykernel_27864\3101870600.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  objective=np.array([['max',5,-10]], dtype=np.object)


array([['max', 5, -10]], dtype=object)

In [3]:
constraint=np.array([[-2,1,'<=',1],[1,-1,'>=',-2],[3,1,'<=',8],[-2,1,'<=',-9],[4,3,'>=',0]], dtype=np.object)
constraint_origin=constraint
constraint_origin

C:\Users\maith\AppData\Local\Temp\ipykernel_27864\1191267947.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  constraint=np.array([[-2,1,'<=',1],[1,-1,'>=',-2],[3,1,'<=',8],[-2,1,'<=',-9],[4,3,'>=',0]], dtype=np.object)


array([[-2, 1, '<=', 1],
       [1, -1, '>=', -2],
       [3, 1, '<=', 8],
       [-2, 1, '<=', -9],
       [4, 3, '>=', 0]], dtype=object)

In [4]:
# Nếu là biến tự do thì ta dùng "?"
condition=np.array([[1,0,'>=',0],[0,1,'?',0]], dtype=np.object)
condition_origin=condition
condition_origin

C:\Users\maith\AppData\Local\Temp\ipykernel_27864\2240793066.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  condition=np.array([[1,0,'>=',0],[0,1,'?',0]], dtype=np.object)


array([[1, 0, '>=', 0],
       [0, 1, '?', 0]], dtype=object)

In [5]:
def check_condition(objective, constraint, condition):
    
    condition2=condition
    flag1=0
    flag2=0
    flag3=0
    for i in range(condition2.shape[0]):
        for j in range(condition2.shape[1]):
            if np.diag(condition2)[i] == 1:
                if condition2[i][j] == '<='and condition2[:,-1][i] == 0  :
                    objective[:,i+1+flag2] = objective[:,i+1+flag2]*-1
                    constraint[:,i+flag2]=constraint[:,i+flag2]*-1
                    condition[i][j] = '>='
                    flag1=flag1+1
                elif condition2[i][j] == '>='and condition2[:,-1][i] == 0  :
                    flag3=flag3+1
                elif condition[:,-1][i] != 0 :
                    temp_objective=pd.DataFrame(objective)
                    newcol=np.vstack([temp_objective.iloc[:,2*i+1-flag1-flag3],temp_objective.iloc[:,2*i+1-flag1-flag3]*-1])
                    temp_objective.insert(2*i+1-flag1-flag3,None,newcol[0].T)
                    temp_objective.insert(2*i+2-flag1-flag3,None,newcol[1].T)
                    temp_objective.drop(labels=2*i+1-flag1-flag3,axis=1,inplace=True)
                    objective=temp_objective
                    objective=temp_objective.values
                    
                    temp_constraint=pd.DataFrame(constraint)
                    newrow=np.zeros(temp_constraint.shape[1],dtype=np.object)
                    newrow[i-flag1-flag3:]=condition2[i,:]                    
                    temp_constraint.loc[temp_constraint.shape[0]+1]=newrow
                    #constraint= np.vstack([constraint, newrow])
                    newcol=np.vstack([temp_constraint.iloc[:,2*i-flag1-flag3],temp_constraint.iloc[:,2*i-flag1-flag3]*-1])
                    temp_constraint.insert(2*i-flag1-flag3,None,newcol[0].T)
                    temp_constraint.insert(2*i+1-flag1-flag3,None,newcol[1].T)
                    temp_constraint.drop(labels=2*i-flag1-flag3,axis=1,inplace=True)
                    constraint=temp_constraint.values
                    
                    
                    newcol=np.zeros(condition.shape[0],dtype=np.object)
                    newrow=np.zeros(condition.shape[1]+1,dtype=np.object)
                    temp_condition=pd.DataFrame(condition)
                    temp_condition.insert(condition.shape[1]-2,None,newcol.T)
                    temp_condition.loc[condition.shape[0]]=newrow
                    temp_condition.iloc[-1,condition.shape[1]-1]='>='
                    temp_condition.iloc[-1,condition.shape[1]-2]=1
                    temp_condition.iloc[i,condition.shape[1]]=0
                    temp_condition.iloc[i,condition.shape[1]-1]='>='
                    condition = np.array(temp_condition)
                    
                    flag2=flag2+1
                elif condition2[i][j] == '?'and condition2[:,-1][i] == 0:
                    temp_objective=pd.DataFrame(objective)
                    newcol=np.vstack([temp_objective.iloc[:,2*i+1-flag1-flag3],temp_objective.iloc[:,2*i+1-flag1-flag3]*-1])
                    temp_objective.insert(2*i+1-flag1-flag3,None,newcol[0].T)
                    temp_objective.insert(2*i+2-flag1-flag3,None,newcol[1].T)
                    temp_objective.drop(labels=2*i+1-flag1-flag3,axis=1,inplace=True)
                    objective=temp_objective
                    objective=temp_objective.values
                    
                    temp_constraint=pd.DataFrame(constraint)
                    
                    #constraint= np.vstack([constraint, newrow])
                    newcol=np.vstack([temp_constraint.iloc[:,2*i-flag1-flag3],temp_constraint.iloc[:,2*i-flag1-flag3]*-1])
                    temp_constraint.insert(2*i-flag1-flag3,None,newcol[0].T)
                    temp_constraint.insert(2*i+1-flag1-flag3,None,newcol[1].T)
                    temp_constraint.drop(labels=2*i-flag1-flag3,axis=1,inplace=True)
                    constraint=temp_constraint.values
                    
                    
                    newcol=np.zeros(condition.shape[0],dtype=np.object)
                    newrow=np.zeros(condition.shape[1]+1,dtype=np.object)
                    temp_condition=pd.DataFrame(condition)
                    temp_condition.insert(condition.shape[1]-2,None,newcol.T)
                    temp_condition.loc[condition.shape[0]]=newrow
                    temp_condition.iloc[-1,condition.shape[1]-1]='>='
                    temp_condition.iloc[-1,condition.shape[1]-2]=1
                    temp_condition.iloc[i,condition.shape[1]]=0
                    temp_condition.iloc[i,condition.shape[1]-1]='>='
                    condition = np.array(temp_condition)
                    
                    flag2=flag2+1
                
    return objective,constraint,condition

objective, constraint, condition = check_condition(objective, constraint, condition)
print('objective:\n',objective)
print('constraint:\n',constraint)
print('condition:\n', condition)

objective:
 [['max' 5 -10 10]]
constraint:
 [[-2 1 -1 '<=' 1]
 [1 -1 1 '>=' -2]
 [3 1 -1 '<=' 8]
 [-2 1 -1 '<=' -9]
 [4 3 -3 '>=' 0]]
condition:
 [[1 0 0 '>=' 0]
 [0 1 0 '>=' 0]
 [0 0 1 '>=' 0]]


C:\Users\maith\AppData\Local\Temp\ipykernel_27864\346678788.py:69: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  newcol=np.zeros(condition.shape[0],dtype=np.object)
C:\Users\maith\AppData\Local\Temp\ipykernel_27864\346678788.py:70: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  newrow=np.zeros(condition.shape[1]+1,dtype=np.object)


In [6]:
def check_constraint(objective, constraint, condition):
    constraint2=constraint
    k=constraint.shape[1]-2
    flag=0
    for i in range(constraint2.shape[0]):
        if constraint[i-flag][k] == ">=":
            constraint[i-flag,:]=constraint[i-flag,:]*-1
            constraint[i-flag][k] = "<="
            
        if constraint2[:,k][i] == "=":
            newrow=np.vstack([constraint[i-flag],constraint[i-flag]*-1])
            newrow[0][k]='<='
            newrow[1][k]='<='
            temp_constraint=pd.DataFrame(constraint)
            #temp_constraint = temp_constraint.drop(labels=i, axis=0)
            temp_constraint.loc[temp_constraint.shape[0]+1]=newrow[0]
            temp_constraint.loc[temp_constraint.shape[0]+2]=newrow[1]
            temp_constraint = temp_constraint.drop(labels=i-flag, axis=0)
            flag=flag+1
                    
            constraint=temp_constraint.values
    return objective,constraint,condition
        
objective, constraint, condition = check_constraint(objective, constraint, condition)
print('objective:\n',objective)
print('constraint:\n',constraint)
print('condition:\n', condition)

objective:
 [['max' 5 -10 10]]
constraint:
 [[-2 1 -1 '<=' 1]
 [-1 1 -1 '<=' 2]
 [3 1 -1 '<=' 8]
 [-2 1 -1 '<=' -9]
 [-4 -3 3 '<=' 0]]
condition:
 [[1 0 0 '>=' 0]
 [0 1 0 '>=' 0]
 [0 0 1 '>=' 0]]


In [7]:
def check_objective(objective, constraint, condition):
    if objective[0][0]=='max':
        objective=objective*-1
        objective[0][0]='min'
    return objective, constraint, condition
objective, constraint, condition = check_objective(objective, constraint, condition)
print('objective:\n',objective)
print('constraint:\n',constraint)
print('condition:\n', condition)

objective:
 [['min' -5 10 -10]]
constraint:
 [[-2 1 -1 '<=' 1]
 [-1 1 -1 '<=' 2]
 [3 1 -1 '<=' 8]
 [-2 1 -1 '<=' -9]
 [-4 -3 3 '<=' 0]]
condition:
 [[1 0 0 '>=' 0]
 [0 1 0 '>=' 0]
 [0 0 1 '>=' 0]]


In [8]:
def convert(objective, constraint, condition):
    c = objective[:,1:]
    c = c.flatten()
    c = c.astype(np.float64)
    
    b = constraint[:, -1]
    b = b.astype(np.float64)
    
    A = np.delete(constraint, [-1,-2], axis = 1)
    A = A.astype(np.float64)
    return A, b, c

In [9]:
A, b, c = convert(objective, constraint, condition)

In [10]:
A

array([[-2.,  1., -1.],
       [-1.,  1., -1.],
       [ 3.,  1., -1.],
       [-2.,  1., -1.],
       [-4., -3.,  3.]])

In [11]:
b

array([ 1.,  2.,  8., -9.,  0.])

In [12]:
c

array([ -5.,  10., -10.])

In [13]:
import numpy as np

# A: ma trận chứa hệ của của các biến trong các ràng buộc
# b: mảng chứa các giá trị bi
# c: mảng chứa hệ số các biến trong hàm mục tiêu

def dantzig_method(A, b, c):
    m, n = A.shape

    # Khởi tạo biến giá trị tối ưu
    z = 0 
    
    # Tính ma trận bổ sung
    T = np.hstack((A, np.eye(m)))
    c_n = np.concatenate((c, np.zeros(m)))
    b_n = b.copy()
    
    # Copy biến ban đầu để so sánh
    A_cop = T.copy()
    c_cop = c_n.copy()
    b_cop = b.copy()
    
    # Tính biến cơ sở ban đầu
    basis = list(range(n, n + m))
    
    while True:
        # Tìm biến vào
        #print("T: ", T)
        
        j = np.argmin(c_n)
        
        if c_n[j] >= 0:
            break
            
        # Tìm biến ra
        ratios = [float('inf')] * m
        for i in range(m):
            if T[i, j] > 0:
                ratios[i] = b_n[i] / T[i, j]
        
        i = np.argmin(ratios)

        # Kiểm tra bài toán không giới nội
        if ratios[i] == float('inf'):
            print("Bài toán không giới nội.")
            return -np.inf, None
        
        # Tính giá trị tối ưu
        z += c_n[j] / T[i, j] * b_n[i]
        # Cập nhật ma trận
        basis[i] = j
        
        #print("T: ", T)
        for k in range(m):
            if k != i:
                b_n[k] -= T[k, j]/T[i,j] * b_n[i]
                T[k, :] -=  T[k, j] / T[i,j] * T[i, :]
        
        b_n[i] /= T[i, j]
        T[i, :] /= T[i, j]       
        c_n -= c_n[j] * T[i, :]
        
        #print("c: ", c_n)
        # Kiểm tra thuật toán có hoàn thành hay không 
        # Nếu Từ vựng mới trùng với từ vựng ban đầu thì dừng thuật toán
        if (c_n == c_cop).all() and (T == A_cop).all() and (b_n == b_cop).all():
            print("Thuật toán lặp vô hạn.")
            return None, None
        
    # Tìm nghiệm tối ưu
    x = np.zeros(n)
    for i in range(m):
        if basis[i] < n:
            x[basis[i]] = b_n[i]
    print("Bài toán có nghiệm duy nhất.")                      
    return z, x 

In [14]:
def leaving_index(c):
    for i, c_i in enumerate(c):
        if c_i < 0:
            return i
    return None

In [15]:
def bland_method(A, b, c):
    m, n = A.shape

    # Khởi tạo biến giá trị tối ưu
    z = 0 
    
    # Tính ma trận bổ sung
    T = np.hstack((A, np.eye(m)))
    c_n = np.concatenate((c, np.zeros(m)))
    b_n = b.copy()
    
    # Copy biến ban đầu để so sánh
    A_cop = T.copy()
    c_cop = c_n.copy()
    b_cop = b.copy()
    
    # Tính biến cơ sở ban đầu
    basis = list(range(n, n + m))
    # Chuyển về dạng chuẩn tắc
    while True:
        
        # Tìm biến vào
        j = leaving_index(c_n)
        if j == None:
            break
            
        # Tìm biến ra
        ratios = [float('inf')] * m
        for i in range(m):
            if T[i, j] > 0:
                ratios[i] = b_n[i] / T[i, j]
        
        i = np.argmin(ratios)

        # Kiểm tra bài toán không giới nội
        if ratios[i] == float('inf'):
            print("Bài toán không giới nội.")
            return -np.inf, None
        
        # Tính giá trị tối ưu
        z += c_n[j] / T[i, j] * b_n[i]
    
        # Cập nhật ma trận
        basis[i] = j
        
        for k in range(m):
            if k != i:
                b_n[k] -= T[k, j]/T[i,j] * b_n[i]
                T[k, :] -=  T[k, j] / T[i,j] * T[i, :]
        
        b_n[i] /= T[i, j]
        T[i, :] /= T[i, j]       
        c_n -= c_n[j] * T[i, :]
        
        # Kiểm tra thuật toán có hoàn thành hay không 
        # Nếu Từ vựng mới trùng với từ vựng ban đầu thì dừng thuật toán
        if (c_n == c_cop).all() and (T == A_cop).all() and (b_n == b_cop).all():
            print("Thuật toán lặp vô hạn.")
            return None, None
       
    # Tìm nghiệm tối ưu
    x = np.zeros(n)
    for i in range(m):
        if basis[i] < n:
            x[basis[i]] = b_n[i]
                           
    return z, x 

In [16]:
def two_phases(A,b,c):

    m, n = A.shape
    # Khởi tạo biến giá trị tối ưu
    z = 0
    # Tính ma trận bổ sung có chứa x0
    c1 = np.concatenate((np.ones(1), np.zeros(m+n)))
    new_col = (-1*np.ones(m)).reshape(-1, 1)
    T = np.hstack((new_col,np.hstack((A, np.eye(m)))))
    b_n = b.copy()


    # Copy biến ban đầu để so sánh
    A_cop = T.copy()
    c_cop = c1.copy()
    b_cop = b.copy()

    # Tính biến cơ sở ban đầu
    basis = list(range(n+1, n + m+1))
    # Chuyển về dạng chuẩn tắc

    #Chọn biến vào
    j = 0
    #Tìm biến ra
    i = np.argmin(b_n)

    
    # Tính giá trị tối ưu
    z += c1[j] / T[i, j] * b_n[i]
    # Cập nhật ma trận
    basis[i] = j
    
    for k in range(m):
        if k != i:
            b_n[k] -= T[k, j]/T[i,j] * b_n[i]
            T[k, :] -=  T[k, j] / T[i,j] * T[i, :]
    
    b_n[i] /= T[i, j]
    T[i, :] /= T[i, j]       
    c1 -= c1[j] * T[i, :]

    #phase 1
    while True:
        # Tìm biến vào
        j = np.argmin(c1)
        
        if c1[j] >= 0:
            break
            
        # Tìm biến ra
        ratios = [float('inf')] * m
        for i in range(m):
            if T[i, j] > 0:
                ratios[i] = b_n[i] / T[i, j]
        
        i = np.argmin(ratios)

        # Kiểm tra bài toán không giới nội hoặc từ vựng tối ưu
        if ratios[i] == float('inf'):
            return -np.inf, None
        
        # Tính giá trị tối ưu
        z += c1[j] / T[i, j] * b_n[i]
        # Cập nhật ma trận
        basis[i] = j
        
        for k in range(m):
            if k != i:
                b_n[k] -= T[k, j]/T[i,j] * b_n[i]
                T[k, :] -=  T[k, j] / T[i,j] * T[i, :]
        
        b_n[i] /= T[i, j]
        T[i, :] /= T[i, j]       
        c1 -= c1[j] * T[i, :]
        # Kiểm tra thuật toán có hoàn thành hay không 
        # Nếu Từ vựng mới trùng với từ vựng ban đầu thì dừng thuật toán
        if (c1 == c_cop).all() and (T == A_cop).all() and (b_n == b_cop).all():
            print("Thuật toán lặp vô hạn.")
            return None, None
        
    #Kiểm tra bài toán có nghiệm khi hoàn thành phase 1
    if np.array_equal(c1,c_cop) == False:
        return None, None
    #Thiết lập hàm mục tiêu cho phase 2
    # c_n = np.concatenate((np.zeros(len(c)), np.zeros(m)))
    c_n = np.zeros(m+n) # trường hợp các biến trên hàm mục tiêu không đủ

    #loại bỏ x0
    T = T[:, 1:]
    T_z = T.copy()
    for i in range(m):
        if basis[i] <= n:
            T_z[i,basis[i]-1] = 0 # làm mất biến thay vào khi thêm vào hàm mục tiêu
            c_n += c[basis[i]-1] * T_z[i,:] #vì basis có tính 0
            z += c[basis[i]-1] * b_n[i]
    #Cập nhật giá trị z cho phase 2
    c_n *= -1
    #Cập nhật lại basis
    basis -= np.ones(len(basis))
    #phase 2

    while True:
        # Tìm biến vào
        j = np.argmin(c_n)
        
        if c_n[j] >= 0:
            break
            
        # Tìm biến ra
        ratios = [float('inf')] * m
        for i in range(m):
            if T[i, j] > 0:
                ratios[i] = b_n[i] / T[i, j]
        
        i = np.argmin(ratios)

        # Kiểm tra bài toán không giới nội
        if ratios[i] == float('inf'):
            print("Bài toán không giới nội.")
            return -np.inf, None
        
        # Tính giá trị tối ưu
        z += c_n[j] / T[i, j] * b_n[i]
        # Cập nhật ma trận
        basis[i] = j
        
        for k in range(m):
            if k != i:
                # x1 = T[k, j]/T[i,j]
                # x2 = b_n[i]
                # b_n[k] -= np.multiply(x1,x2)
                b_n[k] -= (T[k, j]/T[i,j]) * b_n[i]
                T[k, :] -=  T[k, j] / T[i,j] * T[i, :]
        
        b_n[i] /= T[i, j]
        T[i, :] /= T[i, j]
        c_n -= c_n[j] * T[i, :]
        # Kiểm tra thuật toán có hoàn thành hay không 
        # Nếu Từ vựng mới trùng với từ vựng ban đầu thì dừng thuật toán
        if np.array_equal(c_n, c_cop) and np.array_equal(T, A_cop) and np.array_equal(b_n, b_cop):
            print("Thuật toán lặp vô hạn.")
            # Thêm bland vào đây
            return None, None
        
    # Tìm nghiệm tối ưu
    x = np.zeros(n)
    for i in range(m):
        if basis[i] < n:
            if i <= len(b_n):
                x[int(basis[i])] = b_n[i]
            else:
                x[int(basis[i])] = 0
            # try:
            #     idx = int(basis[i])
            #     if idx < 0 or idx >= len(x):
            #         raise IndexError
            #     x[idx] = b_n[i]
            # except (IndexError, ValueError):
            #     print(f"Invalid basis index at i = {i}")
            #     x[basis[i]] = 0      




    return z, x  

In [17]:

z, x = two_phases(A, b, c)
print("z = ", z)
print("x = ", x)

Bài toán không giới nội.
z =  -inf
x =  None


In [18]:
def origin_solution(objective_origin, constraint_origin, condition_origin, z, x):
    if z==None:
        return z,x
    x_origin=np.zeros(constraint_origin.shape[1]-2,dtype=object)
    if objective_origin[0][0]=='max':
        if str(z)=='-inf':
            z='inf'
        elif str(z)=='inf':
            z='-inf'
        else:
            z=-z
    else:
        z=z
    if x!=None:
        for i in range(condition_origin.shape[0]):
            for j in range(i+1,len(x)):
                if condition_origin[:,-2][i]=='?':
                    x_origin[i]= x[i]-x[j]
                if condition_origin[:,-2][i]=='<=':
                    x_origin[i]=-x[i]
                if condition_origin[:,-2][i]=='>=':
                    x_origin[i]=x[i]
    else:
        x_origin=x
                
    return z,x_origin
z_origin,x_origin = origin_solution(objective_origin, constraint_origin, condition_origin, z, x)
print(z_origin)
print(x_origin)

inf
None
